server:
  port: ${PORT:9010}

services:
  gateway: ${GW_URL:http://localhost:8080}

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5555}/${DB_MAIN_NAME:mess}
    username: pas
    password: pas
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    queues:
      messages:
        name: messagesQueue
        durable: true
      callback:
        name: callBackQueue
        durable: true
    exchanges:
      messages:
        name: messagesExchange
        durable: true
        autoDelete: false
    bindings:
      routingKey: messages
