rsa.private-key: private.pem
rsa.public-key: public.pem

server:
  port: ${PORT:8090}

services:
  gateway: ${GW_URL:http://localhost:8080}

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${DB_MAIN_NAME:postgres}
    username: postgres

    password: secret
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

